import { Destination } from '../types/index.js';

export const WORLD_DESTINATIONS: Destination[] = [
  // ================= AFRICA =================
  {
    id: 'lagos',
    name: 'Lagos',
    city: 'Lagos',
    country: 'Nigeria',
    continent: 'Africa',
    flag: '🇳🇬',
    currency: 'NGN',
    priceIndexUSD: 65,
    tag: 'Arts, Coast & Nightlife',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1618828665347-d870c38c95c7?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Nov – Feb (Detty December & Dry Season)',
    visaInfo: 'Visa on Arrival / eVisa for non-ECOWAS citizens',
    plugType: 'Type D & G (230V, 50Hz)',
    language: 'English, Yoruba, Pidgin',
    emergencyNumber: '112 / 767',
    tippingCustom: '5–10% in sit-down restaurants is appreciated',
    description: 'Vibrant cultural mega-city bursting with contemporary art, Atlantic coastline beaches, and buzzing nightlife.',
  },
  {
    id: 'abuja',
    name: 'Abuja',
    city: 'Abuja',
    country: 'Nigeria',
    continent: 'Africa',
    flag: '🇳🇬',
    currency: 'NGN',
    priceIndexUSD: 70,
    tag: 'Parks & Monoliths',
    category: 'Cultural',
    img: 'https://images.unsplash.com/photo-1537372023620-37161b1ad8ac?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Oct – Mar (Mild dry weather)',
    visaInfo: 'Visa on Arrival / eVisa for non-ECOWAS',
    plugType: 'Type D & G (230V, 50Hz)',
    language: 'English, Hausa, Pidgin',
    emergencyNumber: '112',
    tippingCustom: '5–10% in upscale dining',
    description: 'Modern planned capital with broad boulevards, green parks, and the monumental Zuma & Aso Rocks.',
  },
  {
    id: 'abeokuta',
    name: 'Abeokuta',
    city: 'Abeokuta',
    country: 'Nigeria',
    continent: 'Africa',
    flag: '🇳🇬',
    currency: 'NGN',
    priceIndexUSD: 45,
    tag: 'Ancient Rocks & Adire Fabrics',
    category: 'Budget',
    img: 'https://images.unsplash.com/photo-1569706971306-de5d78f6418e?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Nov – Feb',
    visaInfo: 'ECOWAS free entry / eVisa for international',
    plugType: 'Type D & G (230V, 50Hz)',
    language: 'Yoruba, English',
    emergencyNumber: '112',
    tippingCustom: 'Round up small bills',
    description: 'Historic city celebrated for the legendary Olumo Rock fortress and Kemta Adire tie-dye fabric markets.',
  },
  {
    id: 'badagry',
    name: 'Badagry',
    city: 'Badagry',
    country: 'Nigeria',
    continent: 'Africa',
    flag: '🇳🇬',
    currency: 'NGN',
    priceIndexUSD: 40,
    tag: 'Coastal Heritage & Whispering Palms',
    category: 'Cultural',
    img: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Oct – Mar (Sunny Coastal Season)',
    visaInfo: 'ECOWAS free entry / eVisa for international',
    plugType: 'Type D & G (230V, 50Hz)',
    language: 'Yoruba, Ogu (Egun), English, Pidgin',
    emergencyNumber: '112 / 767',
    tippingCustom: '5–10% in beach resorts',
    description: 'Storied coastal sanctuary featuring the historic Point of No Return, First Storey Building (1845), Whispering Palms Lagoon, and peaceful coconut beaches.',
  },
  {
    id: 'dakar',
    name: 'Dakar',
    city: 'Dakar',
    country: 'Senegal',
    continent: 'Africa',
    flag: '🇸🇳',
    currency: 'USD',
    priceIndexUSD: 55,
    tag: 'Atlantic Coast & Gorée Heritage',
    category: 'Cultural',
    img: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Nov – May (Dry Season)',
    visaInfo: 'Visa-free for 90 days for ECOWAS, US & EU / eVisa',
    plugType: 'Type C, D, E & K (230V, 50Hz)',
    language: 'French, Wolof',
    emergencyNumber: '17 (Police) / 18 (Fire)',
    tippingCustom: '5–10% in sit-down dining is appreciated',
    description: 'Vibrant West African Atlantic capital renowned for African Renaissance Monument, Gorée Island history, and surf beaches.',
  },
  {
    id: 'cape-town',
    name: 'Cape Town',
    city: 'Cape Town',
    country: 'South Africa',
    continent: 'Africa',
    flag: '🇿🇦',
    currency: 'ZAR',
    priceIndexUSD: 85,
    tag: 'Table Mountain & Coastal Drives',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Dec – Mar (Warm summer)',
    visaInfo: 'Visa-free for 90 days for many nationalities / eVisa',
    plugType: 'Type D, M & N (230V, 50Hz)',
    language: 'English, Afrikaans, Xhosa',
    emergencyNumber: '10111 / 112',
    tippingCustom: '10–15% standard for good service',
    description: 'Breathtaking coastal city where dramatic mountain peaks meet pristine ocean shores and historic winelands.',
  },
  {
    id: 'nairobi',
    name: 'Nairobi',
    city: 'Nairobi',
    country: 'Kenya',
    continent: 'Africa',
    flag: '🇰🇪',
    currency: 'USD',
    priceIndexUSD: 70,
    tag: 'Urban Wildlife & Coffee Culture',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1580796711202-0a1835905d4a?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Jul – Oct & Jan – Feb',
    visaInfo: 'Electronic Travel Authorization (eTA) required online',
    plugType: 'Type G (240V, 50Hz)',
    language: 'Swahili, English',
    emergencyNumber: '999 / 112',
    tippingCustom: '10% in tourist areas',
    description: 'The world’s only capital city with a national game park teeming with lions and giraffes minutes from downtown.',
  },
  {
    id: 'accra',
    name: 'Accra',
    city: 'Accra',
    country: 'Ghana',
    continent: 'Africa',
    flag: '🇬🇭',
    currency: 'GHS',
    priceIndexUSD: 60,
    tag: 'Heritage, Highlife & Atlantic Surf',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Oct – Mar',
    visaInfo: 'Visa required / Visa on Arrival for African Union & Diaspora',
    plugType: 'Type D & G (230V, 50Hz)',
    language: 'English, Twi, Ga',
    emergencyNumber: '191 / 112',
    tippingCustom: '5–10% appreciated',
    description: 'Warm, hospitable West African coastal capital with lively arts scenes, heritage castles, and vibrant beach lounges.',
  },
  {
    id: 'marrakech',
    name: 'Marrakech',
    city: 'Marrakech',
    country: 'Morocco',
    continent: 'Africa',
    flag: '🇲🇦',
    currency: 'USD',
    priceIndexUSD: 55,
    tag: 'Medina Souks & Palaces',
    category: 'Cultural',
    img: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Mar – May & Sep – Nov',
    visaInfo: 'Visa-free for up to 90 days for US/EU/UK',
    plugType: 'Type C & E (220V, 50Hz)',
    language: 'Arabic, Berber, French',
    emergencyNumber: '19 (Police) / 15 (Fire/Ambulance)',
    tippingCustom: '10–15% in restaurants',
    description: 'Enchanting imperial city with bustling souks, aromatic spices, intricate riads, and palace courtyards.',
  },
  {
    id: 'cairo',
    name: 'Cairo',
    city: 'Cairo',
    country: 'Egypt',
    continent: 'Africa',
    flag: '🇪🇬',
    currency: 'EGP',
    priceIndexUSD: 45,
    tag: 'Pyramids of Giza & The Nile',
    category: 'Cultural',
    img: 'https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Oct – Apr',
    visaInfo: 'Visa on Arrival / eVisa for 40+ countries',
    plugType: 'Type C & F (220V, 50Hz)',
    language: 'Arabic, English',
    emergencyNumber: '122',
    tippingCustom: 'Baksheesh (5–10%) is customary',
    description: 'Ancient cradle of civilization boasting the Great Pyramids of Giza, the Nile, and treasure-filled museums.',
  },
  {
    id: 'zanzibar',
    name: 'Zanzibar',
    city: 'Stone Town',
    country: 'Tanzania',
    continent: 'Africa',
    flag: '🇹🇿',
    currency: 'USD',
    priceIndexUSD: 75,
    tag: 'Turquoise Waters & Spice Island',
    category: 'Tropical',
    img: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Jun – Oct & Dec – Feb',
    visaInfo: 'eVisa or Visa on Arrival ($50–$100)',
    plugType: 'Type D & G (230V, 50Hz)',
    language: 'Swahili, English',
    emergencyNumber: '112',
    tippingCustom: '10%',
    description: 'Idyllic Indian Ocean paradise featuring white sand sandbars, historic Stone Town alleys, and turquoise lagoons.',
  },
  {
    id: 'kigali',
    name: 'Kigali',
    city: 'Kigali',
    country: 'Rwanda',
    continent: 'Africa',
    flag: '🇷🇼',
    currency: 'USD',
    priceIndexUSD: 65,
    tag: 'Clean Hills & Gorilla Gateway',
    category: 'Cultural',
    img: 'https://images.unsplash.com/photo-1588661799793-2736b4129997?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Jun – Sep & Dec – Feb',
    visaInfo: 'Visa on Arrival for all nationalities',
    plugType: 'Type C & J (230V, 50Hz)',
    language: 'Kinyarwanda, English, French',
    emergencyNumber: '112',
    tippingCustom: '5–10%',
    description: 'Africa’s cleanest, safest capital, surrounded by lush rolling hills, vibrant coffee houses, and contemporary art.',
  },
  {
    id: 'mauritius',
    name: 'Mauritius',
    city: 'Port Louis',
    country: 'Mauritius',
    continent: 'Africa',
    flag: '🇲🇺',
    currency: 'USD',
    priceIndexUSD: 110,
    tag: 'Coral Reefs & Volcanic Lagoons',
    category: 'Tropical',
    img: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'May – Dec',
    visaInfo: 'Visa-free 90 days for most nationalities',
    plugType: 'Type C & G (230V, 50Hz)',
    language: 'English, French, Creole',
    emergencyNumber: '999',
    tippingCustom: '10%',
    description: 'Spectacular island nation with sapphire waters, underwater waterfalls, botanical gardens, and luxury beach resorts.',
  },

  // ================= EUROPE =================
  {
    id: 'paris',
    name: 'Paris',
    city: 'Paris',
    country: 'France',
    continent: 'Europe',
    flag: '🇫🇷',
    currency: 'EUR',
    priceIndexUSD: 140,
    tag: 'Eiffel Tower & Fine Art',
    category: 'Luxury',
    img: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Apr – Jun & Sep – Oct',
    visaInfo: 'Schengen Visa',
    plugType: 'Type C & E (230V, 50Hz)',
    language: 'French',
    emergencyNumber: '112',
    tippingCustom: 'Service compris (round up small change or 5%)',
    description: 'Timeless city of light renowned for world-defining museums, cafe culture along the Seine, and iconic architecture.',
  },
  {
    id: 'london',
    name: 'London',
    city: 'London',
    country: 'United Kingdom',
    continent: 'Europe',
    flag: '🇬🇧',
    currency: 'GBP',
    priceIndexUSD: 150,
    tag: 'Royal Parks, West End & Thames',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'May – Sep',
    visaInfo: 'Standard Visitor Visa / ETA',
    plugType: 'Type G (230V, 50Hz)',
    language: 'English',
    emergencyNumber: '999 / 112',
    tippingCustom: '10–12.5% discretionary service charge',
    description: 'Vibrant historic global capital featuring world-class free national museums, royal parks, and premier theater.',
  },
  {
    id: 'rome',
    name: 'Rome',
    city: 'Rome',
    country: 'Italy',
    continent: 'Europe',
    flag: '🇮🇹',
    currency: 'EUR',
    priceIndexUSD: 110,
    tag: 'Colosseum & Roman Piazzas',
    category: 'Cultural',
    img: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Apr – Jun & Sep – Oct',
    visaInfo: 'Schengen Visa',
    plugType: 'Type C, F & L (230V, 50Hz)',
    language: 'Italian',
    emergencyNumber: '112',
    tippingCustom: '1–2€ per person extra is kind',
    description: 'Eternal city of emperors and gelato, home to the Colosseum, Vatican museums, and vibrant trattorias.',
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    city: 'Barcelona',
    country: 'Spain',
    continent: 'Europe',
    flag: '🇪🇸',
    currency: 'EUR',
    priceIndexUSD: 100,
    tag: 'Gaudí Architecture & Tapas',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'May – Jun & Sep – Oct',
    visaInfo: 'Schengen Visa',
    plugType: 'Type C & F (230V, 50Hz)',
    language: 'Spanish, Catalan',
    emergencyNumber: '112',
    tippingCustom: '5–10%',
    description: 'Mediterranean gem famed for the Sagrada Família, gothic quarters, and lively beach promenades.',
  },
  {
    id: 'madrid',
    name: 'Madrid',
    city: 'Madrid',
    country: 'Spain',
    continent: 'Europe',
    flag: '🇪🇸',
    currency: 'EUR',
    priceIndexUSD: 95,
    tag: 'Royal Palace & Flamenco',
    category: 'Cultural',
    img: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Apr – Jun & Sep – Oct',
    visaInfo: 'Schengen Visa',
    plugType: 'Type C & F (230V, 50Hz)',
    language: 'Spanish',
    emergencyNumber: '112',
    tippingCustom: '5–10%',
    description: 'Energetic Spanish capital brimming with world-class art museums, grand plazas, and culinary tapas bars.',
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    city: 'Amsterdam',
    country: 'Netherlands',
    continent: 'Europe',
    flag: '🇳🇱',
    currency: 'EUR',
    priceIndexUSD: 130,
    tag: 'Canal Houses & Cycle Paths',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Apr – May & Sep – Nov',
    visaInfo: 'Schengen Visa',
    plugType: 'Type C & F (230V, 50Hz)',
    language: 'Dutch, English',
    emergencyNumber: '112',
    tippingCustom: '5–10%',
    description: 'Scenic canals, world-famous Van Gogh Museum, historic bridges, and vibrant cafe life.',
  },
  {
    id: 'berlin',
    name: 'Berlin',
    city: 'Berlin',
    country: 'Germany',
    continent: 'Europe',
    flag: '🇩🇪',
    currency: 'EUR',
    priceIndexUSD: 95,
    tag: 'Brandenburg Gate & Arts',
    category: 'Budget',
    img: 'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'May – Sep',
    visaInfo: 'Schengen Visa',
    plugType: 'Type C & F (230V, 50Hz)',
    language: 'German, English',
    emergencyNumber: '112',
    tippingCustom: '5–10%',
    description: 'A city of bold reinvention, historic monuments, museum island, and unrivaled creative culture.',
  },
  {
    id: 'lisbon',
    name: 'Lisbon',
    city: 'Lisbon',
    country: 'Portugal',
    continent: 'Europe',
    flag: '🇵🇹',
    currency: 'EUR',
    priceIndexUSD: 80,
    tag: 'Yellow Trams & Pastel de Nata',
    category: 'Budget',
    img: 'https://images.unsplash.com/photo-1509840841025-9088ba78a826?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Mar – May & Sep – Oct',
    visaInfo: 'Schengen Visa',
    plugType: 'Type C & F (230V, 50Hz)',
    language: 'Portuguese, English',
    emergencyNumber: '112',
    tippingCustom: '5–10%',
    description: 'Sun-drenched coastal capital with vintage trams, historic tiled facades, and fresh Atlantic seafood.',
  },
  {
    id: 'santorini',
    name: 'Santorini',
    city: 'Thira',
    country: 'Greece',
    continent: 'Europe',
    flag: '🇬🇷',
    currency: 'EUR',
    priceIndexUSD: 140,
    tag: 'Caldera Sunsets & White Villas',
    category: 'Luxury',
    img: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Apr – Oct',
    visaInfo: 'Schengen Visa',
    plugType: 'Type C & F (230V, 50Hz)',
    language: 'Greek, English',
    emergencyNumber: '112',
    tippingCustom: '5–10%',
    description: 'Iconic Aegean volcanic island featuring whitewashed cliffside villages and breathtaking sunset vistas.',
  },
  {
    id: 'istanbul',
    name: 'Istanbul',
    city: 'Istanbul',
    country: 'Turkey',
    continent: 'Europe',
    flag: '🇹🇷',
    currency: 'USD',
    priceIndexUSD: 60,
    tag: 'Bosphorus Strait & Hagia Sophia',
    category: 'Budget',
    img: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Apr – May & Sep – Nov',
    visaInfo: 'eVisa online ($50)',
    plugType: 'Type C & F (230V, 50Hz)',
    language: 'Turkish, English',
    emergencyNumber: '112',
    tippingCustom: '5–10%',
    description: 'Where East meets West across the Bosphorus, rich with ancient spice bazaars and grand imperial mosques.',
  },

  // ================= ASIA & OCEANIA =================
  {
    id: 'tokyo',
    name: 'Tokyo',
    city: 'Tokyo',
    country: 'Japan',
    continent: 'Asia',
    flag: '🇯🇵',
    currency: 'JPY',
    priceIndexUSD: 110,
    tag: 'Neon Shrines & Gastronomy',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Mar – May & Oct – Nov',
    visaInfo: 'Japan eVisa / Visa-free',
    plugType: 'Type A & B (100V, 50/60Hz)',
    language: 'Japanese',
    emergencyNumber: '110 / 119',
    tippingCustom: 'No tipping',
    description: 'Futuristic mega-metropolis harmoniously blending ancient Shinto shrines, Michelin gastronomy, and hyper-modern rail.',
  },
  {
    id: 'bali',
    name: 'Bali',
    city: 'Bali',
    country: 'Indonesia',
    continent: 'Asia',
    flag: '🇮🇩',
    currency: 'USD',
    priceIndexUSD: 50,
    tag: 'Emerald Terraces & Surf Sunsets',
    category: 'Tropical',
    img: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Apr – Oct',
    visaInfo: 'e-VoA available for 30 days',
    plugType: 'Type C & F (230V, 50Hz)',
    language: 'Indonesian, Balinese, English',
    emergencyNumber: '112',
    tippingCustom: '5–10%',
    description: 'Enchanting tropical paradise known for terraced jungle valleys, spiritual water temples, and world-class surf breaks.',
  },
  {
    id: 'bangkok',
    name: 'Bangkok',
    city: 'Bangkok',
    country: 'Thailand',
    continent: 'Asia',
    flag: '🇹🇭',
    currency: 'USD',
    priceIndexUSD: 50,
    tag: 'Street Food & Golden Temples',
    category: 'Budget',
    img: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Nov – Feb',
    visaInfo: '60-day Visa-free',
    plugType: 'Type A, B, C & O (220V, 50Hz)',
    language: 'Thai, English',
    emergencyNumber: '1155',
    tippingCustom: '10%',
    description: 'Dynamic metropolis of ornate Chao Phraya river temples, floating markets, and legendary Michelin street food.',
  },
  {
    id: 'singapore',
    name: 'Singapore',
    city: 'Singapore',
    country: 'Singapore',
    continent: 'Asia',
    flag: '🇸🇬',
    currency: 'USD',
    priceIndexUSD: 150,
    tag: 'Marina Bay & Futuristic Gardens',
    category: 'Luxury',
    img: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Year-round',
    visaInfo: 'SG Arrival Card online',
    plugType: 'Type G (230V, 50Hz)',
    language: 'English, Mandarin, Malay, Tamil',
    emergencyNumber: '999',
    tippingCustom: '10% included',
    description: 'Garden city-state with iconic Marina Bay Sands, supertree groves, and diverse Michelin food stalls.',
  },
  {
    id: 'seoul',
    name: 'Seoul',
    city: 'Seoul',
    country: 'South Korea',
    continent: 'Asia',
    flag: '🇰🇷',
    currency: 'USD',
    priceIndexUSD: 85,
    tag: 'K-Culture, Palaces & Night Markets',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Mar – May & Sep – Nov',
    visaInfo: 'K-ETA online',
    plugType: 'Type C & F (220V, 60Hz)',
    language: 'Korean',
    emergencyNumber: '112',
    tippingCustom: 'No tipping',
    description: 'Hyper-trendy capital where modern skyscrapers tower over historic royal palaces and bustling K-beauty districts.',
  },
  {
    id: 'maldives',
    name: 'Maldives',
    city: 'Male',
    country: 'Maldives',
    continent: 'Asia',
    flag: '🇲🇻',
    currency: 'USD',
    priceIndexUSD: 200,
    tag: 'Overwater Bungalows & Coral Atolls',
    category: 'Luxury',
    img: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Nov – Apr',
    visaInfo: 'Free 30-day Visa on Arrival',
    plugType: 'Type D & G (230V, 50Hz)',
    language: 'Dhivehi, English',
    emergencyNumber: '119',
    tippingCustom: '10%',
    description: 'Unmatched tropical archipelago of private atoll resorts, crystal lagoons, manta ray diving, and overwater luxury.',
  },
  {
    id: 'sydney',
    name: 'Sydney',
    city: 'Sydney',
    country: 'Australia',
    continent: 'Asia',
    flag: '🇦🇺',
    currency: 'AUD',
    priceIndexUSD: 155,
    tag: 'Opera House & Bondi Surf',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Sep – Nov & Mar – May',
    visaInfo: 'eVisitor / ETA online visa',
    plugType: 'Type I (230V, 50Hz)',
    language: 'English',
    emergencyNumber: '000',
    tippingCustom: '10%',
    description: 'Iconic harbor metropolis featuring the architectural Sydney Opera House, Harbour Bridge, and golden Bondi Beach.',
  },

  // ================= AMERICAS =================
  {
    id: 'new-york',
    name: 'New York City',
    city: 'New York',
    country: 'United States',
    continent: 'Americas',
    flag: '🇺🇸',
    currency: 'USD',
    priceIndexUSD: 180,
    tag: 'Broadway, Skyline & Central Park',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Apr – Jun & Sep – Nov',
    visaInfo: 'ESTA / B1/B2 Visa',
    plugType: 'Type A & B (120V, 60Hz)',
    language: 'English',
    emergencyNumber: '911',
    tippingCustom: '18–20%',
    description: 'The city that never sleeps: world-class skyline vistas, Broadway theater, Central Park, and diverse global dining.',
  },
  {
    id: 'toronto',
    name: 'Toronto',
    city: 'Toronto',
    country: 'Canada',
    continent: 'Americas',
    flag: '🇨🇦',
    currency: 'CAD',
    priceIndexUSD: 120,
    tag: 'CN Tower & Lake Ontario',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1507992781348-310259076fa0?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'May – Oct',
    visaInfo: 'eTA / Visitor Visa',
    plugType: 'Type A & B (120V, 60Hz)',
    language: 'English, French',
    emergencyNumber: '911',
    tippingCustom: '15–18%',
    description: 'Dynamic multicultural metropolis featuring the iconic CN Tower, scenic islands, and global gastronomy.',
  },
  {
    id: 'rio-de-janeiro',
    name: 'Rio de Janeiro',
    city: 'Rio de Janeiro',
    country: 'Brazil',
    continent: 'Americas',
    flag: '🇧🇷',
    currency: 'USD',
    priceIndexUSD: 70,
    tag: 'Copacabana & Christ the Redeemer',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Dec – Mar',
    visaInfo: 'eVisa / Visa-free for EU',
    plugType: 'Type C & N (127V/220V, 60Hz)',
    language: 'Portuguese',
    emergencyNumber: '190',
    tippingCustom: '10%',
    description: 'Samba rhythms, golden Atlantic sands of Copacabana and Ipanema, and dramatic mountain peaks.',
  },
  {
    id: 'cancun',
    name: 'Cancun',
    city: 'Cancun',
    country: 'Mexico',
    continent: 'Americas',
    flag: '🇲🇽',
    currency: 'USD',
    priceIndexUSD: 90,
    tag: 'Caribbean Beaches & Mayan Ruins',
    category: 'Tropical',
    img: 'https://images.unsplash.com/photo-1510097467424-192d713fd8b2?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Dec – Apr',
    visaInfo: 'Visa-free for US, EU, UK, Canada',
    plugType: 'Type A & B (127V, 60Hz)',
    language: 'Spanish, English',
    emergencyNumber: '911',
    tippingCustom: '10–15%',
    description: 'Turquoise Caribbean waters, all-inclusive beachfront resorts, and ancient Mayan pyramids at Chichen Itza.',
  },
  {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    city: 'Buenos Aires',
    country: 'Argentina',
    continent: 'Americas',
    flag: '🇦🇷',
    currency: 'USD',
    priceIndexUSD: 60,
    tag: 'Tango, Steakhouses & Architecture',
    category: 'Cultural',
    img: 'https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Oct – Dec & Mar – May',
    visaInfo: 'Visa-free 90 days',
    plugType: 'Type C & I (220V, 50Hz)',
    language: 'Spanish',
    emergencyNumber: '911',
    tippingCustom: '10%',
    description: 'The Paris of South America with grand European boulevards, world-class steakhouses, and authentic tango.',
  },

  // ================= MIDDLE EAST =================
  {
    id: 'dubai',
    name: 'Dubai',
    city: 'Dubai',
    country: 'United Arab Emirates',
    continent: 'Middle East',
    flag: '🇦🇪',
    currency: 'AED',
    priceIndexUSD: 130,
    tag: 'Burj Khalifa & Desert Safaris',
    category: 'Luxury',
    img: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Nov – Mar',
    visaInfo: '30-day Visa on Arrival for 70+ nations',
    plugType: 'Type G (230V, 50Hz)',
    language: 'Arabic, English',
    emergencyNumber: '999',
    tippingCustom: '10–15%',
    description: 'Dynamic oasis of skyscraper architecture, luxury beach resorts, traditional gold souks, and desert dunes.',
  },
  {
    id: 'doha',
    name: 'Doha',
    city: 'Doha',
    country: 'Qatar',
    continent: 'Middle East',
    flag: '🇶🇦',
    currency: 'USD',
    priceIndexUSD: 120,
    tag: 'Corniche & Islamic Art Museum',
    category: 'Luxury',
    img: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Nov – Apr',
    visaInfo: 'Free Visa-free entry for 100+ countries',
    plugType: 'Type D & G (240V, 50Hz)',
    language: 'Arabic, English',
    emergencyNumber: '999',
    tippingCustom: '10–15%',
    description: 'Futuristic Gulf city boasting architectural masterpieces, luxury waterfronts, and Souq Waqif heritage.',
  },
];
