import { Destination } from '../types/index.js';

export const WORLD_DESTINATIONS: Destination[] = [
  // --- AFRICA ---
  {
    id: 'lagos',
    name: 'Lagos',
    city: 'Lagos',
    country: 'Nigeria',
    continent: 'Africa',
    flag: '🇳🇬',
    currency: 'NGN',
    priceIndexUSD: 65,
    tag: 'Arts, Coast & Nightlife',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1618828665347-d870c38c95c7?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Nov – Feb (Dry Season & Detty December)',
    visaInfo: 'Visa on Arrival / eVisa required for non-ECOWAS citizens',
    plugType: 'Type D & G (230V, 50Hz)',
    language: 'English, Yoruba, Pidgin',
    emergencyNumber: '112 / 767',
    tippingCustom: '5–10% in sit-down restaurants is appreciated',
    description: 'Vibrant cultural mega-city bursting with contemporary art, Atlantic coastline beaches, and buzzing nightlife.',
  },
  {
    id: 'abuja',
    name: 'Abuja',
    city: 'Abuja',
    country: 'Nigeria',
    continent: 'Africa',
    flag: '🇳🇬',
    currency: 'NGN',
    priceIndexUSD: 70,
    tag: 'Parks & Monoliths',
    category: 'Cultural',
    img: 'https://images.unsplash.com/photo-1537372023620-37161b1ad8ac?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Oct – Mar (Mild weather)',
    visaInfo: 'Visa on Arrival / eVisa for non-ECOWAS',
    plugType: 'Type D & G (230V, 50Hz)',
    language: 'English, Hausa, Pidgin',
    emergencyNumber: '112',
    tippingCustom: '5–10% in upscale dining',
    description: 'Modern planned capital with broad boulevards, green parks, and the monumental Zuma & Aso Rocks.',
  },
  {
    id: 'abeokuta',
    name: 'Abeokuta',
    city: 'Abeokuta',
    country: 'Nigeria',
    continent: 'Africa',
    flag: '🇳🇬',
    currency: 'NGN',
    priceIndexUSD: 45,
    tag: 'Ancient Rocks & Adire Fabrics',
    category: 'Budget',
    img: 'https://images.unsplash.com/photo-1569706971306-de5d78f6418e?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Nov – Feb',
    visaInfo: 'ECOWAS free entry / eVisa for international',
    plugType: 'Type D & G (230V, 50Hz)',
    language: 'Yoruba, English',
    emergencyNumber: '112',
    tippingCustom: 'Round up small bills',
    description: 'Historic city celebrated for the legendary Olumo Rock fortress and vibrant Kemta Adire tie-dye fabric markets.',
  },
  {
    id: 'cape-town',
    name: 'Cape Town',
    city: 'Cape Town',
    country: 'South Africa',
    continent: 'Africa',
    flag: '🇿🇦',
    currency: 'ZAR',
    priceIndexUSD: 85,
    tag: 'Table Mountain & Coastal Drives',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Dec – Mar (Warm summer)',
    visaInfo: 'Visa-free for 90 days for many nationalities / eVisa',
    plugType: 'Type D, M & N (230V, 50Hz)',
    language: 'English, Afrikaans, Xhosa',
    emergencyNumber: '10111 / 112',
    tippingCustom: '10–15% standard for good service',
    description: 'Breathtaking coastal city where dramatic mountain peaks meet pristine ocean shores and historic winelands.',
  },
  {
    id: 'nairobi',
    name: 'Nairobi',
    city: 'Nairobi',
    country: 'Kenya',
    continent: 'Africa',
    flag: '🇰🇪',
    currency: 'USD',
    priceIndexUSD: 75,
    tag: 'Urban Wildlife & Coffee Culture',
    category: 'Cultural',
    img: 'https://images.unsplash.com/photo-1580796711202-0a1835905d4a?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Jul – Oct & Jan – Feb',
    visaInfo: 'Electronic Travel Authorization (eTA) required online',
    plugType: 'Type G (240V, 50Hz)',
    language: 'Swahili, English',
    emergencyNumber: '999 / 112',
    tippingCustom: '10% in tourist areas',
    description: 'The world’s only capital city with a national game park teeming with lions and giraffes minutes from downtown.',
  },
  {
    id: 'accra',
    name: 'Accra',
    city: 'Accra',
    country: 'Ghana',
    continent: 'Africa',
    flag: '🇬🇭',
    currency: 'GHS',
    priceIndexUSD: 60,
    tag: 'Heritage, Highlife & Atlantic Surf',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Oct – Mar',
    visaInfo: 'Visa required / Visa on Arrival for Diaspora',
    plugType: 'Type D & G (230V, 50Hz)',
    language: 'English, Twi, Ga',
    emergencyNumber: '191 / 112',
    tippingCustom: '5–10% appreciated',
    description: 'Warm, hospitable West African coastal capital with lively arts scenes, heritage castles, and vibrant beach lounges.',
  },

  // --- ASIA ---
  {
    id: 'tokyo',
    name: 'Tokyo',
    city: 'Tokyo',
    country: 'Japan',
    continent: 'Asia',
    flag: '🇯🇵',
    currency: 'JPY',
    priceIndexUSD: 110,
    tag: 'Neon Shrines & Culinary Precision',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Mar – May (Cherry Blossom) & Oct – Nov',
    visaInfo: 'eVisa available for many countries / Visa-free 90 days',
    plugType: 'Type A & B (100V, 50/60Hz)',
    language: 'Japanese (English signage in transit)',
    emergencyNumber: '110 (Police) / 119 (Medical)',
    tippingCustom: 'No tipping! Exceptional hospitality is included.',
    description: 'Futuristic mega-metropolis harmoniously blending ancient Shinto shrines, Michelin gastronomy, and hyper-modern rail.',
  },
  {
    id: 'bali',
    name: 'Bali (Ubud & Seminyak)',
    city: 'Bali',
    country: 'Indonesia',
    continent: 'Asia',
    flag: '🇮🇩',
    currency: 'USD',
    priceIndexUSD: 50,
    tag: 'Emerald Terraces & Surf Sunsets',
    category: 'Tropical',
    img: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Apr – Oct (Dry Season)',
    visaInfo: 'Electronic Visa on Arrival (e-VoA) available for 30 days',
    plugType: 'Type C & F (230V, 50Hz)',
    language: 'Indonesian, Balinese, English widely spoken',
    emergencyNumber: '112 / 110',
    tippingCustom: '5–10% in upscale venues',
    description: 'Enchanting tropical paradise known for terraced jungle valleys, spiritual water temples, and world-class surf breaks.',
  },

  // --- EUROPE ---
  {
    id: 'paris',
    name: 'Paris',
    city: 'Paris',
    country: 'France',
    continent: 'Europe',
    flag: '🇫🇷',
    currency: 'EUR',
    priceIndexUSD: 140,
    tag: 'Haussmann Boulevards & Fine Art',
    category: 'Luxury',
    img: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Apr – Jun & Sep – Oct',
    visaInfo: 'Schengen Visa / 90 days visa-free for eligible passports',
    plugType: 'Type C & E (230V, 50Hz)',
    language: 'French (English widely in hotels/museums)',
    emergencyNumber: '112 (EU Universal)',
    tippingCustom: 'Service compris (round up small change or 5%)',
    description: 'Timeless city of light renowned for world-defining museums, cafe culture along the Seine, and iconic architecture.',
  },
  {
    id: 'london',
    name: 'London',
    city: 'London',
    country: 'United Kingdom',
    continent: 'Europe',
    flag: '🇬🇧',
    currency: 'GBP',
    priceIndexUSD: 150,
    tag: 'Royal Parks, West End & Gastropubs',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'May – Sep (Long sunny days)',
    visaInfo: 'Standard Visitor Visa / ETA for eligible countries',
    plugType: 'Type G (230V, 50Hz)',
    language: 'English',
    emergencyNumber: '999 / 112',
    tippingCustom: '10–12.5% often added as discretionary service charge',
    description: 'Vibrant historic global capital featuring world-class free national museums, royal parks, and premier theater.',
  },

  // --- MIDDLE EAST & AMERICAS ---
  {
    id: 'dubai',
    name: 'Dubai',
    city: 'Dubai',
    country: 'United Arab Emirates',
    continent: 'Middle East',
    flag: '🇦🇪',
    currency: 'AED',
    priceIndexUSD: 130,
    tag: 'Architectural Marvels & Desert Safaris',
    category: 'Luxury',
    img: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Nov – Mar (Pleasant winter)',
    visaInfo: '30-day Visa on Arrival for 70+ nations / Tourist eVisa',
    plugType: 'Type G (230V, 50Hz)',
    language: 'Arabic, English universally spoken',
    emergencyNumber: '999 (Police) / 998 (Ambulance)',
    tippingCustom: '10–15% standard in dining',
    description: 'Dynamic oasis of skyscraper architecture, luxury beach resorts, traditional gold souks, and desert dunes.',
  },
  {
    id: 'new-york',
    name: 'New York City',
    city: 'New York',
    country: 'United States',
    continent: 'Americas',
    flag: '🇺🇸',
    currency: 'USD',
    priceIndexUSD: 180,
    tag: 'Broadway, Skyline & World Flavors',
    category: 'Popular',
    img: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&h=600&fit=crop&auto=format',
    bestTimeToVisit: 'Apr – Jun & Sep – Nov',
    visaInfo: 'ESTA for Visa Waiver countries / B1/B2 tourist visa',
    plugType: 'Type A & B (120V, 60Hz)',
    language: 'English',
    emergencyNumber: '911',
    tippingCustom: '18–20% standard in restaurants and cabs',
    description: 'The city that never sleeps: world-class skyline vistas, Broadway theater, Central Park, and diverse global dining.',
  },
];
